language: ruby
cache: bundler
sudo: false
rvm:
- 2.7
deploy:
  provider: rubygems
  gem: bog
  on:
    tags: true
    all_branches: true
    repo: opsunit/bog
    ruby: 2.7
  api_key:
    secure: u8rdkyxcXSPyzsCmUO69HaDNsziOQ/Y+6E0hZwj4NKwZdu/BfP6ictr3gpLfh1Nw509PasB1mEWxpeBWOcZDInLzNfJOj9xvXk2UxxdRqnzNPfsvEQsvoYwZETVTrJqMKoHuIQH5SGcz++Ko3ISrg8fbVGnD24vmjNI7DXmR37Q=
